### ISSUE TITLE
Shopping List UI & Class 

### ISSUE THREAD

**Issue by yashShelatkar** [Eclipse2552/Tafe17S204#6]
Hey, guys, I have just noticed we still have to do one more branch and class for the Shopping List, Does anyone knows Who's doing it? 

![ken](https://user-images.githubusercontent.com/25059239/31594106-9e183bf2-b27a-11e7-8299-e88d68ac4d15.PNG)

**Comment by Eclipse2552** [comment]
The shopping list is Kenny's feature
